#!/bin/bash
echo "Running flake8..."
flake8 app.py
echo "Running black..."
black --line-length 79 --check app.py
echo "Running isort..."
isort --line-length 79 --check --diff app.py
echo "Everythinks okay."
